version: "3.8"
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    networks:
      bbs_network:
        ipv4_address: 172.30.0.10

networks:
  bbs_network:
    external: true
