import { Inter } from 'next/font/google';

import Header from '@/components/Header/Header';

import CookiesProviderX from './_provider/cookiesProviderX';
import QueryClientProviderX from './_provider/queryClientProviderX';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <CookiesProviderX>
          <QueryClientProviderX>
            <Header />
            {children}
          </QueryClientProviderX>
        </CookiesProviderX>
      </body>
    </html>
  );
}
